# Generated by Django 2.0.1 on 2019-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '作者表',
                'db_table': '作者表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='图书名称')),
                ('category', models.IntegerField(choices=[(1, 'python'), (2, 'Go'), (3, 'Linux')], verbose_name='图书类别')),
                ('pub_time', models.DateField(verbose_name='出版日期')),
                ('author', models.ManyToManyField(to='SerDemo.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '图书表',
                'db_table': '图书表',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='出版社名称')),
            ],
            options={
                'verbose_name_plural': '出版社表',
                'db_table': '出版社表',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=None, to='SerDemo.Publisher', verbose_name='出版社'),
        ),
    ]
