# Generated by Django 2.2.7 on 2020-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('token', models.UUIDField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'vip'), (2, 'vvip'), (3, '普通')], default=3)),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': '用户表',
            },
        ),
    ]
