# Generated by Django 3.0.2 on 2020-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('roles', models.ManyToManyField(blank=True, to='ppp.Role', verbose_name='拥有的角色')),
            ],
        ),
    ]
