# Generated by Django 2.0.1 on 2019-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_is_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
