# Generated by Django 2.0.1 on 2019-10-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20191025_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='p_id',
            field=models.ForeignKey(blank=True, help_text='对于费菜单权限需要选择一个菜单权限，用户点击非菜单权限时，关联的菜单权限默认展开', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='rbac.Permission', verbose_name='关联的权限'),
        ),
    ]
