# Generated by Django 2.0.1 on 2019-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='URL的别名'),
        ),
    ]
