# Generated by Django 2.0.1 on 2019-10-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='1', max_length=64, verbose_name='图标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default=2, max_length=32, verbose_name='一级菜单名称'),
            preserve_default=False,
        ),
    ]
