# Generated by Django 2.0.1 on 2019-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('web', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
