# Generated by Django 2.0.1 on 2019-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191108_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
