# Generated by Django 2.0.1 on 2019-11-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.PositiveIntegerField(verbose_name='班级(期)')),
                ('price', models.IntegerField(verbose_name='学费')),
                ('start_date', models.DateField(verbose_name='开班日期')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='结业日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course', verbose_name='课程')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.School', verbose_name='校区')),
                ('tec_teacher', models.ManyToManyField(blank=True, related_name='teach_teacher', to='web.UserInfo', verbose_name='任课老师')),
            ],
        ),
    ]
