# Generated by Django 2.0.1 on 2019-11-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20191109_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'department_title': '教质部'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tec_teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'department__title__in': ['Linux教学部', 'python教学部']}, related_name='teach_teacher', to='web.UserInfo', verbose_name='任课老师'),
        ),
    ]
