# Generated by Django 2.0.1 on 2019-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_consultrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(1, '在校生'), (2, '应届毕业'), (3, '半年以内'), (4, '半年至一年'), (5, '一年至三年'), (6, '三年至五年'), (7, '五年以上')], null=True, verbose_name='工作经验'),
        ),
    ]
