# Generated by Django 2.0.1 on 2019-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_paymentrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='web.ClassList', verbose_name='已报班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
