# Generated by Django 2.0.1 on 2019-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(null=True, upload_to='course/%Y-%m', verbose_name='课程的图片'),
        ),
    ]
