# Generated by Django 2.0.1 on 2019-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('token', models.UUIDField()),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': '用户表',
            },
        ),
    ]
