# Generated by Django 2.0.1 on 2019-11-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authDemo', '0002_auto_20191127_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'vip'), (2, 'vvip'), (3, '普通')], default=3),
        ),
    ]
