# Generated by Django 2.0.1 on 2019-10-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='state',
        ),
    ]
